Add warmup to ema cross algorithm
QuantConnect/Lean pull request #4831
Opened 2020-10-07 23:46 UTC by DerekMelchin

#### Description

Add indicator warmup to EmaCrossUniverseSelectionAlgorithm.

#### Related Issue

Close #3212

#### Motivation and Context

The old algorithms didn't have indicator warmup.

#### Requires Documentation Change

No.

#### How Has This Been Tested?

Run in the web terminal.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2020-10-09 16:56 UTC, AlexCatarino requested changes
Thank you for the update, @DerekMelchin .
I left some comments in the Python version that are also valid for C#.

2020-10-09 16:56 UTC, AlexCatarino commented on Algorithm.Python/EmaCrossUniverseSelectionAlgorithm.py
> +class EmaCrossUniverse(QCAlgorithm):
The main class and file name should share the same name: `EmaCrossUniverseSelectionAlgorithm`.

2020-10-09 16:56 UTC, AlexCatarino commented on Algorithm.Python/EmaCrossUniverseSelectionAlgorithm.py
> +            # Get history for all new symbols. If empty, log and return the selected -- WOW!
Please remove the "WOW!". We could add more comments to this method. Before line 74, state that we will use CoarseFundamental.AdjustedPrice for symbols that have been added before. Before line 77, state that we select symbols that are trending upward (fast > low).

2020-10-09 16:56 UTC, AlexCatarino commented on Algorithm.Python/EmaCrossUniverseSelectionAlgorithm.py
> +        if self.can_trade:
Instead of using `self.can_trade` we might want to use `if self.symbols` and clear the list after the trades are placed.

2020-10-09 16:56 UTC, AlexCatarino commented on Algorithm.Python/EmaCrossUniverseSelectionAlgorithm.py
> +        self.SetEndDate(2020,1,15)
Let's keep the original date range.

2020-10-09 16:56 UTC, AlexCatarino commented on Algorithm.Python/EmaCrossUniverseSelectionAlgorithm.py
> +        return self.symbols
In the former algorithm, we choose the symbols with the highest scale
```python
self.scale = (fast - slow) / ((fast + slow) / 2.0)
```
also there is a tolerance in the fast > slow condition:
```
if symbolData.IsReady and symbolData.fast > symbolData.slow * self.tolerance:
    self.symbols.append(symbol)
```

2020-10-13 22:38 UTC, jaredbroad commented on Algorithm.CSharp/EmaCrossUniverseSelectionAlgorithm.cs
> +
Read through [MS Naming Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines) and revert most of the variable name changes in the C# version.

2020-10-13 22:39 UTC, jaredbroad commented
Closing as too far from where it needs to be.

2020-10-13 22:39 UTC, closed without merging