Local Object Store Temp Directory
QuantConnect/Lean pull request #4880
Opened 2020-10-21 00:14 UTC by C-SELLERS

#### Description

Create a temp storage folder for LocalObjectStore to use when `GetFilePath` creates a copy of the object in the store. Also adjust dispose() and tests to reflect this change.

#### Related Issue

Closes #4811 

#### Motivation and Context

`LocalObjectStore`'s `GetFilePath` currently writes a copy of a requested object to a file in the ObjectStore's storage directory and returns this copies path; this works fine until you start Lean again and the copy is now loaded into the LocalObjectStore as its own object. To resolve this I have created a temp folder in which these copies can live and be used by the requester. This way LocalObjectStore will not pick up those files as objects for the store leading to duplicates.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

All regressions ran and passed, LocalObjectStore tests all pass, Travis tests pass in docker

Verified behaviour in Issue #4811 does not occur

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2020-10-22 14:47 UTC, Martin-Molinero approved these changes
Thanks for the tests! 👍

2020-10-22 19:07 UTC, jaredbroad requested changes
IMHO AddTick, Create Temp folders -- are warning signals for a quick fix hiding an underlying design issue. When we see that we should reflect on what the underlying cause and motivations that got us to this point were.

LocalObjectStore should likely just _return the local file path_ which would eliminate the creation of duplicates. Cloud concerns should be addressed separately.

2020-10-24 00:07 UTC, Martin-Molinero commented on Engine/Storage/LocalObjectStore.cs
>                          File.Delete(path);
I think `PersistData()` should clear the directory before writing to disk and we can remove this delete from here?

2020-10-24 00:07 UTC, Martin-Molinero commented on Tests/Common/Storage/LocalObjectStoreTests.cs
> +                Assert.IsTrue(File.Exists(path));
Nice tests! We should also add the 'Delete' case: We add a key that gets persisted and later we delete it. When we create a new object store it shouldn't re load it

2020-10-26 14:38 UTC, Martin-Molinero commented on Engine/Storage/LocalObjectStore.cs
>          public string GetFilePath(string key)
Realized we need this guy to be virtual since its calling `PersistData()` now

2020-10-27 13:32 UTC, Martin-Molinero approved these changes

2020-10-27 13:32 UTC, Martin-Molinero commented on Tests/Common/Storage/LocalObjectStoreTests.cs
> +        public void DeletedObjectIsNotReloaded()
Cool! 👍

2020-10-31 00:36 UTC, merged