Bug 4809 Docker Run Script Fixes and Improvements
QuantConnect/Lean pull request #4922
Opened 2020-11-06 20:46 UTC by C-SELLERS

#### Description

Changes to our Docker run scripts (run_docker.sh/bat & run_docker_notebook.sh/bat):
- Remove dependency for coreutils on Linux/Mac
- Bash scripts handle already running containers
- Mirror .sh changes to .bat scripts to maintain uniform functionality
- Store results in ./Results dir by default
- Update readmes with any functional changes

Special thanks to @kazazes for starting these changes

#### Related Issue

Closes #4809 
Closes #4810 

#### Motivation and Context

Coreutils problem mentioned in #4809 
Some quality of life improvements as well for easy use in linux environemnt

#### Requires Documentation Change

Readmes have been updated

#### How Has This Been Tested?

Ran a three variations of both scripts on Ubuntu 20.04 and Windows 10

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2020-11-09 16:24 UTC, Martin-Molinero requested changes
Nice improvements, leaving some requests

2020-11-09 16:24 UTC, Martin-Molinero commented on Research/readme.md
> +         IMAGE=quantconnect/lean:latest
same here `lean` -> `research`?

2020-11-09 16:24 UTC, Martin-Molinero commented on Research/run_docker_notebook.sh
> +# fall back to defaults on empty input without
typo `without` ?

2020-11-09 16:24 UTC, Martin-Molinero commented on run_docker.bat
> +set DEFAULT_RESULTS_DIR=%CURRENT_DIR%\Results
`\Results` think `\` isn't required? I'm get `Enter absolute path to store results [default: ...\Lean\\Results]`

2020-11-09 16:24 UTC, Martin-Molinero commented on run_docker.bat
> +    set /p DEBUGGING="Would you like to debug C#? (Requires mono debugger attachment) [default: N]: "
`run_docker.sh` allows specifying `Python directory` should we add it here too?

2020-11-09 16:24 UTC, Martin-Molinero commented on run_docker.sh
> +    -v $RESULTS_DIR:/Results \
I think we should normalize the behavior across all docker scripts, whether we use `-v` or `--mount`

2020-11-09 16:24 UTC, Martin-Molinero commented on run_docker.sh
> +if [ "$($SUDO docker container inspect -f '{{.State.Running}}' $CONTAINER_NAME)" == "true" ]; then
I'm getting:
```
root@ns569941:/home/martin/Lean# ./run_docker.sh
Docker image [default: quantconnect/lean:latest]:
Path to Lean config.json [default: ./Launcher/config.json]:
Path to Data directory [default: ./Data]:
Path to Results directory [default: ./Results]:
Path to Python directory [default: ./Algorithm.Python/]:
Would you like to debug C#? (Requires mono debugger attachment) [default: N]:
Results directory /home/martin/Lean/Results does not exist; creating it now
./run_docker.sh: line 145: syntax error near unexpected token `)'
./run_docker.sh: line 145: `    ($SUDO docker stop $CONTAINER_NAME))'
```

2020-11-09 16:54 UTC, C-SELLERS commented on run_docker.sh
> +if [ "$($SUDO docker container inspect -f '{{.State.Running}}' $CONTAINER_NAME)" == "true" ]; then
🤔

2020-11-11 12:38 UTC, Martin-Molinero approved these changes
Changes look good 👍 
Suggest just before the `docker run` we first do `docker pull %IMAGE%` in the different scripts, found a weird behavior that if executing the `run_docker_notebook.bat` using a console (doesn't happen if executed directly) and the latest image is not present it won't pull it and just end immediately, took me while to understand why it was happening 😅

2020-11-11 17:41 UTC, C-SELLERS commented
Gotcha! Just added a option to update the image, by default it is set to yes! Just didn't want to force updates if someone is running it offline with local data for backtesting.

2020-11-11 17:43 UTC, C-SELLERS commented
Also, thats very weird ? I haven't had that happen when running from command line 🤔 Even with an outdated image. But either way I think the auto update of the image is a good feature to tack on!

2020-11-11 18:48 UTC, merged