Adds DeM indicator
QuantConnect/Lean pull request #5002
Opened 2020-12-06 05:47 UTC by aarjaneiro

Creates the DeMarker Indicator (DeM), an oscillator-type indicator measuring changes in terms of an asset's High and Low tradebar values. 

#### Description

Adds the DeMark indicator. 
#### Related Issue
#4918 

#### Motivation and Context

Added feature due to request.

#### How Has This Been Tested?

Added a test comparing results to those obtained in https://github.com/dmitriiweb/tapy (using the same CSV but combining Date and Time and making it into a .txt). The values in the test data was generated using the DeM indicator as implemented in TaPy. 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x ] I have added tests to cover my changes. 
- [x ] All new and existing tests passed.
- [ x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2020-12-07 14:12 UTC, AlexCatarino requested changes
Thank you, @aarjaneiro!
I left some comments for changes that are mostly style concerns.
However, one constructor is missing, the one that doesn't require the name.
```csharp
public DeMarkerIndicator(int period, MovingAverageType type = MovingAverageType.Simple)
```

2020-12-07 14:12 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +        private decimal DeMax;
We don't need these class variables, since their values are not carried to the next iteration.

2020-12-07 14:12 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +        private IndicatorBase<IndicatorDataPoint> _MAmin;
Nit: I think they should be names `_maxMA` and `_minMA`;

2020-12-07 14:12 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +            _period = period;
We could convert `WarmUpPeriod` to auto-property:
```csharp
WarmUpPeriod = period;
```
and remove `_period` class variable.

2020-12-07 14:12 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +                var DeMark = currentValue > 0m ? _MAmax.Current.Value / currentValue : 0m;
Not required change, just FYI: `IndicatorBase` is implicitly converted to decimal, using `Currect.Value`, so we don't need to use it:
```csharp
var denominator = _maxMA + _minMA;
return currentValue > 0m ? _maxMA / denominator : 0m;
```

2020-12-07 14:12 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +            if (IsReady)
Nit: we could flip this if-condition to reduce nesting:
```csharp
if (!IsReady)
{
    return 0m;
}
```

2020-12-07 23:12 UTC, aarjaneiro commented
Thanks @AlexCatarino! I implemented the requested changes.

2020-12-10 15:31 UTC, AlexCatarino requested changes
Thank you for the updates, @aarjaneiro !
Please check out extra requests below.

2020-12-10 15:31 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +            : this($"DeM({period},{type})", period)
The `type` parameter is not passed to `this`:
```csharp
: this($"DeM({period},{type})", period, type)
```

2020-12-10 15:31 UTC, AlexCatarino commented on Indicators/DeMarkerIndicator.cs
> +        private IndicatorBase<IndicatorDataPoint> _minMA;
These fields could be `readonly` since they are only defined once in the constructor.

2020-12-10 15:39 UTC, AlexCatarino commented on Algorithm/QCAlgorithm.Indicators.cs
> +            var deMarkerIndicator = new DeMarkerIndicator(name, period);
The `type` is not been passed to the constructor.

2020-12-11 22:43 UTC, aarjaneiro commented on Indicators/IndicatorBase.cs
> +        protected Dictionary<SecurityIdentifier, T> _previousInput = new Dictionary<SecurityIdentifier, T>();
Correct, it is not necessarily -- I will revert that (and definitely will be checking over my IDE settings as I did not manually change that).

2020-12-11 23:38 UTC, AlexCatarino approved these changes

2020-12-12 01:56 UTC, jaredbroad requested changes

2020-12-12 02:46 UTC, aarjaneiro commented on Algorithm/QCAlgorithm.Indicators.cs
> +        public DeMarkerIndicator DeM(Symbol symbol, int period, MovingAverageType type, Resolution? resolution = null, Func<IBaseData, TradeBar> selector = null)
No problem, I updated the naming across the modified files!

2020-12-14 22:26 UTC, jaredbroad approved these changes

2020-12-14 22:26 UTC, jaredbroad commented
Thank you @aarjaneiro

2020-12-15 11:29 UTC, merged