Named Args Unit Tests
QuantConnect/Lean pull request #5381
Opened 2021-03-10 21:43 UTC by C-SELLERS

#### Description

Add unit test and regression for new Named Arguments feature of PythonNet 

#### Related Issue

N/A

#### Motivation and Context

New PythonNet supports KWargs

#### Requires Documentation Change

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-03-10 22:54 UTC, Martin-Molinero commented on Algorithm.Python/NamedArgumentsRegression.py
> +        symbol = self.AddEquity(ticker="SPY", resolution=Resolution.Daily).Symbol
Let's change the order and assert it still works & would be nice to make **all** calls use named arguments really 🚀

2021-03-11 16:22 UTC, Martin-Molinero requested changes
Almost there 👍

2021-03-11 16:22 UTC, Martin-Molinero commented on Algorithm.Python/NamedArgumentsRegression.py
> +            self.Debug("Purchased Stock")
Missing named arguments I can see:
`for config in self.SubscriptionManager.SubscriptionDataConfigService.GetSubscriptionDataConfigs(symbol):`
`self.SetHoldings("SPY", 1)`
`self.Debug("Purchased Stock")`

unused 
```
from QuantConnect.Indicators import *
import numpy as np
```

2021-03-11 16:22 UTC, Martin-Molinero commented on Tests/Python/PythonNetTests.cs
> +    public class PythonNetTests
Let's rename the fixture and file to something like NamedArgumentTests, each test should be a different type or named arguments use case I think

2021-03-16 23:52 UTC, jaredbroad approved these changes
Awesome to see named args!!

2021-03-16 23:53 UTC, merged