Bug broken regressions fixes
QuantConnect/Lean pull request #5421
Opened 2021-03-23 23:38 UTC by C-SELLERS

#### Description

Fix the currently broken regressions tests

#### Related Issue

N/A

#### Motivation and Context

Some of our regression tests that we rely on for testing Lean are broken, thankfully there are only a few and seem to be related to recent additions such as #5389 and #5379 

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

After these updates all regression pass as expected except two.

These two are `BasicTemplateIndexAlgorithm` and `IndexOptionCallITMGreeksExpiryRegressionAlgorithm`

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-03-23 23:40 UTC, C-SELLERS commented
Hey @gsalaz98 , do you mind checking out the two remaining broken regressions? 

- `BasicTemplateIndexAlgorithm`
-  `IndexOptionCallITMGreeksExpiryRegressionAlgorithm`


I think they were broken on addition and I'm not sure how they should be acting 😄

2021-03-24 00:47 UTC, gsalaz98 commented
> 
> 
> Hey @gsalaz98 , do you mind checking out the two remaining broken regressions?
> 
>     * `BasicTemplateIndexAlgorithm`
> 
>     * `IndexOptionCallITMGreeksExpiryRegressionAlgorithm`
> 
> 
> They were broken on addition and I'm not sure how they should be acting 😄

`IndexOptionCallITMGreeksExpiryRegressionAlgorithm` is expected to be broken for now, but I think I never got around to updating `BasicTemplateIndexAlgorithm` w/ the push for index options.

2021-03-25 22:46 UTC, jaredbroad commented on Algorithm.CSharp/IndexOptionCallOTMExpiryRegressionAlgorithm.cs
> +        public Language[] Languages { get; } = { Language.CSharp };
@gsalaz98 please add a commit to make sure these pass in python as well

2021-03-25 22:46 UTC, jaredbroad requested changes
Tests should run in python

2021-03-26 23:01 UTC, jaredbroad approved these changes

2021-03-29 20:34 UTC, jaredbroad approved these changes

2021-03-29 20:35 UTC, merged