Live Consolidator Bug Fix
QuantConnect/Lean pull request #5429
Opened 2021-03-26 18:02 UTC by C-SELLERS

#### Description

There was an issue observed with live data where period count based consolidators would only emit bars every other period.

Below is an example of a 1 hour consolidator in master, as you can see the  timing does not emit a bar for 11am or 1 pm
```
2021-03-18 18:00:00 : 	2021-03-18 14:00:00.919081 :: SPY: O: 394.83 H: 396.129 L: 394.69 C: 396.035 V: 7630551
2021-03-19 14:00:00 : 	2021-03-19 10:00:00.861888 :: SPY: O: 389.89 H: 390.2 L: 387.42 C: 388.54 V: 11107174
*** MISSING 11AM? ***
2021-03-19 16:00:00 : 	2021-03-19 12:00:00.800336 :: SPY: O: 389.835 H: 390.88 L: 388.33 C: 390.52 V: 10067133
*** MISSING 1PM? ***
2021-03-19 18:00:00 : 	2021-03-19 14:00:00.865996 :: SPY: O: 390.9455 H: 391.36 L: 390.24 C: 391.09 V: 6182512
```

To remedy the issue I had to adjust the logic in the consolidator update to allow the aggregation of a new bar if the bars `EndTime` was past `_lastEmit` time instead of just looking at the bars `Time` (Its start time)

An example of the issue before:
- 9AM -10AM bar streamed at 10:00:00 AM
- Consolidator aggregates because last emit is DateMin (first update)
- Scan takes the stream time 10:00:00.8 AM, checks that we have a bar, and emits because it past 10 (bar EndTime)
- 
- 10AM - 11AM bar streamed at 11:00:00.5 AM
- Consolidator does not aggregate because last emit time was 10:00:00.8 which is > 10AM bar start time
- Scan takes stream time 11:00:00.5 AM, checks that we have a bar, and it is `null` because we did not aggregate. No emit

Now that check to see if we should aggregate goes against bar `endTime`, so 10:00:00.8 <  11, and it aggregates successfully.

#### Related Issue

N/A

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

All unit tests still pass, same for regressions.

Used a simulated live data feed to test bar consolidation was correct
Also added a unit test that does red -> green from master to this branch

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-04-02 18:22 UTC, jaredbroad commented on Tests/Common/Data/PeriodCountConsolidatorTests.cs
> +            Assert.IsTrue(consolidator.WorkingBar.Time == new DateTime(2015, 04, 13, 3, 0, 0));
Please add another unit test to literally cover the 2pm, 3pm, 4pm case for hourly bars. 95%+ of algorithms won't get data past 4pm until the following morning, but it'll seem like a bug if they don't get the 4pm bar until the next day.

2021-04-02 18:23 UTC, jaredbroad requested changes
Please add some more unit test coverage of different market close scenarios

2021-04-05 14:39 UTC, Martin-Molinero commented on Common/Data/Consolidators/PeriodCountConsolidatorBase.cs
>                  _lastEmit = IsTimeBased && _workingBar != null ? _workingBar.Time.Add(Period ?? TimeSpan.Zero) : data.Time;
Here `_lastEmit` should be rounded? But bellow in `public override void Scan(DateTime currentLocalTime)` we set `_lastEmit` with a different logic, just `currentLocalTime` which **might not be rounded the bug right**? if it also used the bar time the issue shouldn't happen?

2021-04-05 22:28 UTC, Martin-Molinero approved these changes

2021-04-06 00:05 UTC, merged