Adds ETF(...) to UniverseDefinitions
QuantConnect/Lean pull request #5873
Opened 2021-08-23 18:34 UTC by gsalaz98

#### Description

Adds shortcut to allow adding universes with pre-defined universe functions, e.g. `Universe.ETF(Symbol, ...)`

Various `UniverseDefinitions` members were axed in this PR, and as such might cause breaking changes for users using QC500 universe explicitly.

Adds ETF constituents universe framework regression algorithm (C#/Python)
#### Related Issue

N/A
#### Motivation and Context

Improve developer ergonomics
#### Requires Documentation Change

Yes, QC500 is gone and Universe.ETF has been added
#### How Has This Been Tested?

Modified regression algorithms to use new shortcut with AddUniverse and added new regression algorithms using Framework
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-08-23 19:58 UTC, Martin-Molinero requested changes
Cool! A few test cases still missing 👍

2021-08-23 19:58 UTC, Martin-Molinero commented on Algorithm/UniverseDefinitions.cs
> +                Symbol.Create(indexTicker, SecurityType.Index, market),
The overloads accepting a string ticker throw a null reference exception, market can't be null. Let's add a tests covering the cases too

2021-08-23 23:08 UTC, Martin-Molinero approved these changes
Thanks!

2021-08-24 00:00 UTC, Martin-Molinero commented on Algorithm.Python/QuantConnect.Algorithm.Python.csproj
> +      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
nit - maybe we can go back to existing implementation regarding the imports? seems we didn't use `CopyToOutputDirectory`

2021-08-24 17:39 UTC, Martin-Molinero commented on Algorithm.CSharp/ETFConstituentUniverseRSIAlphaModelAlgorithm.cs
> +        public List<ETFConstituentData> Constituents = new List<ETFConstituentData>();
Believe this information will be available through the cache of the underlying see https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityCache.cs#L410 and it's usages, would be a nice example usage of it 👍

2021-08-24 17:39 UTC, Martin-Molinero commented on Algorithm.CSharp/ETFConstituentUniverseRSIAlphaModelAlgorithm.cs
> +        }
Don't think this is required?
`.ToList();` in `return Constituents.Select(x => x.Symbol).ToList();` not required either?
The cleaner & simpler the better 👍

2021-08-24 17:39 UTC, Martin-Molinero commented on Algorithm.CSharp/ETFConstituentUniverseRSIAlphaModelAlgorithm.cs
> +                    allReady = allReady && rsiData.Rsi.Update(new IndicatorDataPoint(bar.Symbol, bar.EndTime, bar.Close));
I think could avoid the need to update the RSI manually & waiting for a warmup if used the `algo.RSI()` ?

2021-08-24 22:53 UTC, Martin-Molinero approved these changes

2021-08-24 23:16 UTC, jaredbroad commented
🎉🎉

2021-08-25 14:22 UTC, merged