Market profile indicator
QuantConnect/Lean pull request #5891
Opened 2021-08-31 21:02 UTC by Marinovsky

#### Description
Two Market profile modes implemented: TimeProfile and Volume Profile.

#### Related Issue

 https://github.com/QuantConnect/Lean/issues/4770

#### Motivation and Context

Market Profile reveals several factors that provide you with
an idea of the trading activity taking place in the markets.
Monitoring the market action will enable you to determine
the type of day that is developing, whether a price trend has
started, what the value area is, the type of activity (initiative
or responsive) taking place, whether the activity is continuing
or changing from the previous day, and whether the market is
trending or bracketing. 

#### Requires Documentation Change

These changes will require updates to the indicators documentation, showing the new indicator and explaning how it works and the parameters need it.

#### How Has This Been Tested?

Using a Google Collaborative notebook (https://colab.research.google.com/drive/16oMViM6SwK4FRGTztxH23xgEE1QH0d23?usp=sharing) and the Python Market Profile library shown in the issue with IBM historical prices from 02/01/2020 to 31/01/2020 from Yahoo finance it was calculated the Market Profile with TPO (Time Price Opportunity) and VOL(Volume Profile) modes while manually rolling a period of three. Then those values were appended into two .csv files with the IBM historical prices previously mentioned, those files are called tp_datatest.csv for TimeProfile tests and vp_datatest.csv for VolumeProfile tests. Finally, using TestIndicator from TestHelper it was made an assertion for each Market Profile value in each mentioned mode.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-08-31 23:01 UTC, Martin-Molinero requested changes
Nice work @Marinovsky! Great first PR 🙌 
Leaving some requests and some code styling request changes

2021-09-01 00:30 UTC, Marinovsky commented on Indicators/MarketProfile.cs
> +        }
Do You mean, add the meaning of price or to make a new object called price?

2021-09-01 00:33 UTC, Marinovsky commented on Indicators/MarketProfile.cs
> +        private readonly decimal _roundoff;
Well I only use `_roundoff` to store the `roundoff` parameter, could it be `RoundAmount` or `RoundParameter`?

2021-09-01 01:02 UTC, Marinovsky commented on Indicators/MarketProfile.cs
> +                if (DataPoints.Values[i] > DataPoints.Values[Max_idx])
But then I should use `DataPoints.FindIndex(a => a.Contains(maxValue)` which would take linear time, because I need the index of the close price with maximum volume.

2021-09-01 02:23 UTC, Marinovsky commented on Indicators/MarketProfile.cs
> +            }
But I only need to know if the Key is in the Dictionary, not if there's a key associated with certain value in the dictionary, because the value of the key is being updated by the time.

2021-09-02 18:06 UTC, Martin-Molinero approved these changes
Nice one!
Leaving minor comments and as final request suggest testing it in the cloud and charting the indicators values in a plot with an assets price and volume as a final graphical sanity test. Let's add those chart images into the PR description too 👍

2021-09-02 18:06 UTC, Martin-Molinero commented on Tests/Indicators/TimeProfileTests.cs
> +            var time = DateTime.Today;
nit - Suggest replacing `DateTime.Today` for just creating a `DateTime(2020, 8, 1)`

2021-09-02 18:06 UTC, Martin-Molinero commented on Indicators/MarketProfile.cs
> +        private SortedList<decimal, decimal> VolumePerPrice { get; }
Should there be a public access for this information? Returning a new copy
```
        private SortedList<decimal, decimal> _volumePerPrice;

        public SortedList<decimal, decimal> VolumePerPrice => new SortedList<decimal, decimal>(_volumePerPrice);
```

2021-09-03 16:44 UTC, Marinovsky commented
Indicator's values plot
![image](https://user-images.githubusercontent.com/47573394/132040163-77617278-38b2-4cf9-9f36-d71d9036f910.png)

2021-09-03 17:03 UTC, Marinovsky commented
Time Profile indicator's values plot
![image](https://user-images.githubusercontent.com/47573394/132042215-43315df2-3214-43b2-8ac8-2ce2bf725ff8.png)

2021-09-03 22:05 UTC, Martin-Molinero approved these changes

2021-09-03 23:18 UTC, merged

2021-09-04 08:35 UTC, ikamanu commented
Great work and timely too --there is an effort currently underway to add VolumeProfile to Lean, but it seems like you beat us to it, @Marinovsky! :)

Question: is the histogram data easily accessible?  Specifically, I'd like to be able to detect the shape of the volume profile distribution, and would need to be able to inspect the data in order to do so.

See attached image for example of 'shape'.  I aim to detect this by measuring skewness, kurtosis, mean, median and mode. 

Thanks for this good work!

<img width="1387" alt="Screen Shot 2021-08-22 at 12 24 28 AM" src="https://user-images.githubusercontent.com/6181572/132088435-8df799ee-c13e-4bd4-acee-b307b3beae3d.png">

2021-09-06 16:01 UTC, Marinovsky commented
> Great work and timely too --there is an effort currently underway to add VolumeProfile to Lean, but it seems like you beat us to it, @Marinovsky! :)
> 
> Question: is the histogram data easily accessible? Specifically, I'd like to be able to detect the shape of the volume profile distribution, and would need to be able to inspect the data in order to do so.
> 
> See attached image for example of 'shape'. I aim to detect this by measuring skewness, kurtosis, mean, median and mode.
> 
> Thanks for this good work!
> 
> <img alt="Screen Shot 2021-08-22 at 12 24 28 AM" width="1387" src="https://user-images.githubusercontent.com/6181572/132088435-8df799ee-c13e-4bd4-acee-b307b3beae3d.png">

Hi @ikamanu, thanks!

Regarding your question: sure, the histogram data is accessible, the method VolumePerPrice returns a SortedList where close values are the keys and the volume for each of them are the values.