Bug 5904 minimum order size rejected order
QuantConnect/Lean pull request #5949
Opened 2021-09-28 19:15 UTC by Marinovsky

Update SymbolsPropertiesDB and Crypto Brokerage Models (QuantConnect#5904)
#### Description

- Update symbols-properties-database.csv with a minimum order size parameter for crypto assets
- Add tests to check if the the SymbolsPropertiesDatabase is loading properly the Minimum Order Size data
- Update Binance, Bitfinex, Kraken and GDAX brokerages models in order to take into account the order size when placing or updating an order
- Create new method IsOrderSizeValid() in default brokerage model in order to check if the order size is valid
- Create new class TestHelpers() to provide useful methods for the brokerages tests
- Add BTCUSD Bitfinex hourly historical data from October 2013 to check Bitfinex brokerage model
- Add tests to check if Binance, Bitfinex, Kraken and GDAX models are taking into account the order size when placing an order
- Add regression test to check if Bitfinex brokerage model is taking into account the order size when placing or updating an order
#### Related Issue

 https://github.com/QuantConnect/Lean/issues/5904

#### Motivation and Context

With this changes the helper methods such as SetHoldings and CalculateOrderSize should not result in a quantity that will be rejected by the brokerage minimum order size.
#### Requires Documentation Change

This changes don't require changes or updates to documentation
#### How Has This Been Tested?

- To check the Symbol Properties Data base was loading properly the minimum order size parameter we assert the value is loading with a the value of a random crypto asset extracted manually from the symbol-properties-database.csv
- To check the crypto brokerages models were taking into account the order size when submiting an order we assert an order with a size less than the allowed and an order with a valid size
- To check the behavior at a system level we write a regression algoritm that first tries to place an order with an invalid size, then tries to update an order with an order with an invalid size and finally places and update an order with a valid size
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2021-09-28 20:52 UTC, Martin-Molinero requested changes
Awesome! leaving a few minor requests

2021-09-28 20:52 UTC, Martin-Molinero commented on Algorithm.CSharp/BuyBTCWithLessThanOneDollarAlgorithm.cs
> +    public class BuyBTCWithLessThanOneDollarAlgorithm : QCAlgorithm, IRegressionAlgorithmDefinition
- `BuyBTCWithLessThanOneDollarAlgorithm` let's rename him to something like `MinimumOrderSizeRegressionAlgorithm`
- Let's add a xml summary description for the algorithm `...This algorithm asserts that the minimum order size is respected..etc`

2021-09-28 20:52 UTC, Martin-Molinero commented on Algorithm.CSharp/BuyBTCWithLessThanOneDollarAlgorithm.cs
> +            SetCash(1);
>  SetCash(1);

Why? Let's remove this if not required, the simpler 10x better 👍

2021-09-28 20:52 UTC, Martin-Molinero commented on Algorithm.CSharp/BuyBTCWithLessThanOneDollarAlgorithm.cs
> +            AddCrypto("BTCUSD", Resolution.Minute, Market.Bitfinex);
> Market.Bitfinex

Specifying the market shouldn't be required, let's remove it 👌. Default resolution is already Minute too

2021-09-28 20:52 UTC, Martin-Molinero commented on Algorithm.CSharp/BuyBTCWithLessThanOneDollarAlgorithm.cs
> +                var closeOrder = MarketOrder("BTCUSD", 0.0002);
> var closeOrder =

Is not required?

2021-09-28 20:52 UTC, Martin-Molinero commented on Common/Brokerages/BinanceBrokerageModel.cs
> +        /// <returns></returns>
Missing docs, let's review all the changes for missing docs 👍 

> using static QuantConnect.StringExtensions; & using System.Linq;

Not required, let's review all changes for none required imports

2021-09-28 20:52 UTC, Martin-Molinero commented on Common/Brokerages/BinanceBrokerageModel.cs
> +            if (!IsValidOrderSize(security, order.AbsoluteQuantity, out message))
Cool! `order.AbsoluteQuantity` can just send quantity since `IsValidOrderSize` is already calling Math.Abs on it, which seems like the right think 👌

2021-09-28 20:52 UTC, Martin-Molinero commented on Common/Brokerages/GDAXBrokerageModel.cs
> +            if(!IsValidOrderSize(security, order.AbsoluteQuantity, out message))
Sweet!

2021-09-28 20:52 UTC, Martin-Molinero commented on Common/Brokerages/KrakenBrokerageModel.cs
> -        public override bool CanUpdateOrder(Security security, Order order, UpdateOrderRequest request, out BrokerageMessageEvent message)
Let's revert this change since it's not required, this version even has the missing docs 👍

2021-09-28 20:52 UTC, Martin-Molinero commented on Engine/TransactionHandlers/BrokerageTransactionHandler.cs
> +                BrokerageMessageEvent message;
Unrequired changes?

2021-09-28 20:52 UTC, Martin-Molinero commented on Engine/TransactionHandlers/BrokerageTransactionHandler.cs
> +                    WaitForOrderSubmission(ticket);
Don't think this PR should be changing this?

2021-09-28 20:52 UTC, Martin-Molinero commented on Tests/Common/Brokerages/BinanceBrokerageModelTests.cs
> +        private readonly BinanceBrokerageModel _unit = new BinanceBrokerageModel();
`_unit` let's rename this guy 👍

2021-09-28 20:52 UTC, Martin-Molinero commented on Tests/Common/Brokerages/BinanceBrokerageModelTests.cs
> +            Assert.AreEqual(isValidOrderQuantity, _unit.CanSubmitOrder(TestsHelpers.GetSecurity(symbol: "BTCEUR", market: Market.Binance, quoteCurrency: "EUR"), order.Object, out message));
cool! 👍

2021-09-28 20:52 UTC, Martin-Molinero commented on Data/symbol-properties/symbol-properties-database.csv
> -
Unrequired changes, let's revert 👍

2021-09-28 20:52 UTC, Martin-Molinero commented on Common/Securities/SymbolProperties.cs
> +        /// </summary>
For pairs like forex or crypto we should specify in the docs in what unit is this expected to be expressed in, believe this is in the Base currency, right?

2021-09-28 20:52 UTC, Martin-Molinero commented on Data/symbol-properties/symbol-properties-database.csv
> +binance,CAKEUSDT,crypto,CAKEUSDT,USDT,1,0.00100000,0.00100000,CAKEUSDT,0.01000000
We have some weird ending zeros in some of these, think we can lose them? 😁

2021-09-30 12:01 UTC, Martin-Molinero approved these changes
Sweet! last minor comments

2021-09-30 20:35 UTC, Martin-Molinero approved these changes

2021-09-30 21:17 UTC, jaredbroad approved these changes

2021-09-30 21:30 UTC, merged