Feature 5157 micro futures update
QuantConnect/Lean pull request #6190
Opened 2022-02-07 22:32 UTC by Marinovsky

#### Description

- Update MHDB, SPDB, `Futures.cs` and `FuturesExpiryFunctions.cs` with Micro Futures from https://www.cmegroup.com/markets/products.html#cleared=Futures&search=Micro&sortField=group
To extract the symbol properties and trading hours of the micro futures it was used the CME Group API and the following Python codes:
```Python
def WriteMicroProperties(micro):
  token = POST()
  # open the file in the write mode
  with open('micros.csv', 'w', newline='') as f:
    # create the csv writer
    writer = csv.writer(f)

    # write a row to the csv file
    for symbol in micro:
      data = GET(symbol, token)
      
      symbolProperties = []
      symbolProperties.append(str(data['_embedded']['products'][0]['exchangeClearing']).lower())
      symbolProperties.append(symbol)
      symbolProperties.append("future")
      symbolProperties.append(data['_embedded']['products'][0]['productName'])
      symbolProperties.append(data['_embedded']['products'][0]['priceQuotation'])
      symbolProperties.append(data['_embedded']['products'][0]['priceMultiplier'])
      symbolProperties.append(data['_embedded']['products'][0]['defaultMinTick'])
      if ("pxUnitOfMeasureQty" in data['_embedded']['products'][0]):
        symbolProperties.append(data['_embedded']['products'][0]['pxUnitOfMeasureQty'])
      else:
        symbolProperties.append(1)
      if (data['_embedded']['products'][0]['priceQuotation']!=None):
        symbolProperties.append("")
        symbolProperties.append(data['_embedded']['products'][0]['minGlobexOrdQty'])
        symbolProperties.append(1)
      
      writer.writerow(symbolProperties)
```
```Python
categories={
    "FOREIGN EXCHANGE" : ["cme", "6A"],
    "ENERGY": ["nymex", "22"],
    "METALS": ["comex", "AUP"],
    "INTEREST RATE": ["cme", "GE"],
    "EQUITY": ["cme", "ES", ]
}
def write_json2(micro, filename='market-hours-database.json'):
    with open(filename,'r+') as file:
          # First we load existing data into a dict.
        file_data = json.load(file)
        token = POST()
        # Join new_data with file_data inside emp_details
        for symbol in micro:
          data = GET(symbol, token)
          assetClass = data['_embedded']['products'][0]['assetSubClass']
          market = data['_embedded']['products'][0]['exchangeClearing']
          if market == "CBT":
            market = "CBOT"
          market = str(market).lower()
          file_data['entries']['Future-'+market+'-'+str(symbol)] = file_data['entries']['Future-'+categories[assetClass][0]+'-'+categories[assetClass][1]]
          print(symbol)
        # Sets file's current position at offset.
        file.seek(0)
        # convert back to json.
        json.dump(file_data, file, indent = 2)
```

The results obtained by the python codes were then checked and edited, if necessary, manually accordingly to similar futures in the SPDB and MHDB
#### Related Issue

#5157 
#### Motivation and Context

This change will contribute to enable users to use Micro futures in their algorithms
#### Requires Documentation Change

This change does not require an update to documentation
#### How Has This Been Tested?

- There was used the same tests for the other futures
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2022-02-08 00:18 UTC, Martin-Molinero requested changes
Awesome! 🍬 
Leaving a couple of minor comments and requests

2022-02-08 00:18 UTC, Martin-Molinero commented on Data/symbol-properties/symbol-properties-database.csv
> +cme,MBT,future,Micro Bitcoin Futures,USD,0.1,5.0,1.0,,1.0,100.0
Bitcoin needs the 100x `price_magnifier`? Same question for `MES` since `ES` doesn't?

2022-02-08 00:18 UTC, Martin-Molinero commented on Data/symbol-properties/symbol-properties-database.csv
> +cme,MNH,future,MICRO USD/CNH FUTURES,IPNT,10000.0,0.0001,1.0
nit `MICRO USD/CNH FUTURES` Think we should normalize the caps here

2022-02-08 00:18 UTC, Martin-Molinero commented on Data/symbol-properties/symbol-properties-database.csv
> +comex,MGC,future,Micro Gold Futures,USD,10.0,0.1,1,,000000000001,100
Some comment about the multiplier, we should sanity test these guys 💯

2022-02-09 23:37 UTC, jaredbroad approved these changes

2022-02-10 20:45 UTC, merged

2022-11-03 23:35 UTC, AssetOverflow commented
Hi, I keep getting a margin call error and this:

Runtime Error: Futures do not allow specifying a leveraged target, since they are traded using margin which already is leveraged. Possible target buying power goes from -1 to 1, target provided is: -1.2832092789625097036394355907 in FutureMarginModel.cs:line 118 

is there anyone that could help me?

Would I somehow adjust SetLeverage?

Here is my code.. 

from AlgorithmImports import *
from math import floor


class AoFuturesGame(QCAlgorithm):
    def Initialize(self):
        # self.SetBrokerageModel(
        #     BrokerageName.InteractiveBrokersBrokerage, AccountType.Margin
        # )
        self.SetStartDate(2022, 6, 1)
        self.SetCash(10000)
        self.es = self.AddFuture(Futures.Indices.MicroNASDAQ100EMini).SetFilter(timedelta(0), timedelta(days=90))
        # self.mnq.SetFilter(0, 90)
        self.Settings.FreePortfolioValuePercentage = 0.30

    def OnMarginCallWarning(self) -> None:
        self.Error("You recieved a Margin Call Warning.")

    def OnData(self, slice):
        for chain in slice.FutureChains:
            self.popularContracts = [
                contract for contract in chain.Value if contract.OpenInterest > 1000
            ]

            if len(self.popularContracts) == 0:
                continue
            sortedByOIContracts = sorted(
                self.popularContracts, key=lambda k: k.OpenInterest, reverse=True
            )

            self.liquidContract = sortedByOIContracts[0]

            if not self.Portfolio.Invested:
                self.SetHoldings(self.liquidContract.Symbol, 1)