Warm up EmaCrossAlphaModel indicators
QuantConnect/Lean pull request #6270
Opened 2022-03-28 23:55 UTC by Marinovsky

#### Description

- Warm up `EmaCrossAlphaModel.cs` and `EmaCrossAlphaModel.py` indicators
- Add unit tests to check the behavior is the expected one
- Fix regression test `CompositeAlphaModelFrameworkAlgorithm.cs`. It turns out the period from the start and end date was less than the default period given to the indicators in the EmeCrossAlphaModel, then those indicators were never ready so `Update()` method never returned an insight. Then, when the indicators of EmaCrossAlpha model were warmed up, the statistics of the regression algorithm changed.
#### Related Issue

#6167
#### Motivation and Context

With this change users will be able to use default EmaCrossAlphaModel even when the period of time between the start and end date is less than the period of time of the fast or slow EMA indicators
#### Requires Documentation Change

This change does not require an update to documentation
#### How Has This Been Tested?

There was created EmaCrossAlpha models in C# and Python and then asserted their indicators were already warmed up when changes are done
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2022-03-28 23:59 UTC, AlexCatarino commented on Algorithm.Framework/Alphas/EmaCrossAlphaModel.cs
>                      var slow = algorithm.EMA(added.Symbol, _slowPeriod, _resolution);
The indicators need to be created by their constructor and registered to a consolidator, so we can remove the subscription to the consolidator when the security is removed.

2022-03-29 00:02 UTC, AlexCatarino requested changes
Thank you for the update, @Marinovsky.
I am requesting a change to improve the algorithm speed that uses this Alpha. If we don't remove the consolidators that are created under the hood when we use a helper method such as `EMA`, the algorithm manager will have a lot of unused consolidators to update.

2022-03-29 17:05 UTC, AlexCatarino approved these changes

2022-03-30 20:37 UTC, Martin-Molinero requested changes
Thanks for the fixes! 💯 Leaving a few minor requests

2022-04-01 15:15 UTC, Martin-Molinero approved these changes

2022-04-01 15:15 UTC, merged