Add example algo of call calendar spread with SPXW
QuantConnect/Lean pull request #6907
Opened 2023-01-26 05:05 UTC by LouisSzeto

#### Description
To add example algorithm of SPXW weekly index options for Call Calendar Spread option strategy.

#### Related Issue
NA

#### Motivation and Context
Lack of combo order examples with index weeklies.

#### Requires Documentation Change
Add the link of example in the Call Calendar Spread option strategy page.

#### How Has This Been Tested?
NA

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
   non-breaking change, `/Data` does not have data for regression
- [X] All new and existing tests passed.
- [X] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-01-26 15:26 UTC, jhonabreul approved these changes
Nice!

2023-01-26 21:06 UTC, AlexCatarino requested changes
Thank you, @LouisSzeto .
I let some comments to improve consistency and follow the repo coding style.

2023-01-26 21:06 UTC, AlexCatarino commented on Algorithm.Python/IndexOptionCallCalendarSpreadAlgorithm.py
> +                 for x in legs])
We can simplify this with:
```python
        quantity = self.Portfolio.TotalPortfolioValue // \
            sum([abs(self.Securities[x.Symbol].Price * x.Quantity * 
                 (self.multiplier if x.Symbol.ID.SecurityType == SecurityType.IndexOption else 1))
                 for x in legs])
```

2023-02-02 19:34 UTC, AlexCatarino approved these changes

2023-02-02 20:33 UTC, merged