Add Relative Volume (RVOL) Indicator
QuantConnect/Lean pull request #6956
Opened 2023-02-11 20:50 UTC by abolfazlghalandary

#### Description
Since i'm new to the Repo and haven't found some useful doc to help to implement #4165, I will appreciate any step to step help to make this PR applicable for merging.
- How to chart the added Indicator? A link to doc is sufficient.
- Is the Implemented Indicator correct?
I will write tests after finding out above answers.

The changes are:
Add RelativeVolume class
Add RVOL method in QCAlgorithm.Indicators class

#### Related Issue
Closes #4165

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-02-12 16:25 UTC, abolfazlghalandary commented
I used RelativeDailyVolume tests and the Data Set attached to the issue. Are the tests OK?
Could you please guide on how to pass the tests? I can't find out how the data set calculated the RVOL value.

2023-02-15 15:13 UTC, jhonabreul requested changes
Thank you for your contribution! 😁 

Just leaving a few comments for you to get this merge ready and help you with the indicator testing. I'll be here if you have any more questions.

2023-02-15 15:13 UTC, jhonabreul commented on Indicators/RelativeVolume.cs
> +        }
Usually in Lean constructors are placed at the top, after attributes and properties, and before any other methods.

2023-02-23 17:36 UTC, Martin-Molinero commented
Hello @abolfazlghalandary! It seems we've missed detecting that this indicator was already implemented, see comment https://github.com/QuantConnect/Lean/issues/4165#issuecomment-1442172231, sorry for the trouble.
There are other good first issues we've tagged if your interested https://github.com/QuantConnect/Lean/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

2023-02-23 17:36 UTC, closed without merging