Add `McClellanOscillator` & `McClellanSummationIndex` Indicator
QuantConnect/Lean pull request #7038
Opened 2023-03-03 16:17 UTC by LouisSzeto

#### Description
Add `McClellanOscillator` & `McClellanSummationIndex` Indicator

#### Related Issue
closes #4060

#### Motivation and Context
newly requested feature

#### Requires Documentation Change
Add section in Indicator Reference, but should automatically handled by code generators

#### How Has This Been Tested?
Added unit tests, and official external source from McClellan Financial

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [X] I have added tests to cover my changes. 
- [X] All new and existing tests passed.
- [X] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-03-06 23:30 UTC, AlexCatarino requested changes
Thank you for the implementation, @LouisSzeto!
I left some comments on the helper methods names, and ask for a clarification.

2023-03-06 23:30 UTC, AlexCatarino commented on Algorithm/QCAlgorithm.Indicators.cs
> +        public McClellanOscillator MO(Symbol[] symbols, int fastPeriod = 19, int slowPeriod = 39, Resolution? resolution = null, Func<IBaseData, TradeBar> selector = null)
We should rename it `MOSC` since the other oscillators' name end with `OSC`: `ADOSC` and `ULTOSC`.

2023-03-06 23:30 UTC, AlexCatarino commented on Indicators/McClellanSummationIndex.cs
> +                // Avoid double updating for the first point
We should improve this description because it's not clear why double updating happens.

2023-03-06 23:30 UTC, AlexCatarino commented on Tests/Indicators/McClellanSummationIndexTests.cs
> +            _mcClellanSummationIndex.Value = -629.68m;
Please use `-606.25m` to fix the unit tests. We need to use some reverse engineering here.

2023-03-07 13:45 UTC, AlexCatarino approved these changes

2023-03-07 14:40 UTC, jaredbroad commented
Nice clean code; thank you @AlexCatarino @LouisSzeto

2023-03-07 18:38 UTC, Martin-Molinero approved these changes

2023-03-07 19:19 UTC, merged