Fixes EquityFillModel.StopMarketFill
QuantConnect/Lean pull request #7042
Opened 2023-03-03 21:22 UTC by AlexCatarino

#### Description
These unit tests cover new scenarios:
- Cannot trigger on quote data (QuoteBar or TickRype.Quote);
- Adds missing test for tick data (TickType.Trade)
- Unfavorable gap (see #4545)
- Worst-case scenario: fill at bid/ask price if the stop is triggered on close.

#### Related Issue
Closes #6972 and #4545

#### Motivation and Context
Improve modeling.

#### Requires Documentation Change
No.

#### How Has This Been Tested?
Old and new unit tests.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-03-07 13:25 UTC, Martin-Molinero commented on Common/Orders/Fills/EquityFillModel.cs
> +            if (endTimeUtc <= order.Time) return fill;
I think we can eventually move all this logic above to a shared method given it's being reused, can be in it's own PR with no behavior change 👍

2023-03-07 13:50 UTC, jaredbroad requested changes
Minor comments

2023-03-07 13:50 UTC, jaredbroad commented on Common/Messages/Messages.Orders.Fills.cs
> +                return Invariant($@"Warning: Due to an unfavorable gap at {endTime} {security.Exchange.TimeZone}, order filled using the open price ({open})");
Please remove "Warning:"

2023-03-07 13:50 UTC, jaredbroad commented on Common/Orders/Fills/EquityFillModel.cs
> +                var trades = asset.Cache.GetAll<Tick>().Where(x => x.TickType == TickType.Trade && x.Price > 0);
When is price 0?

2023-03-07 13:50 UTC, jaredbroad commented on Common/Orders/Fills/EquityFillModel.cs
> +            var tradeHigh = 0m;
Normally this is tradeLow = Decimal.MaxValue, tradeHigh = Decimal.MinValue for the initial state.

2023-03-08 15:36 UTC, AlexCatarino commented on Common/Orders/Fills/EquityFillModel.cs
> -                var trades = asset.Cache.GetAll<Tick>().Where(x => x.TickType == TickType.Trade && x.Price > 0);
I propose we remove `&& x.Price > 0` in the PR to address this request:
https://github.com/QuantConnect/Lean/pull/7042#discussion_r1127852198

2023-03-08 19:43 UTC, jaredbroad approved these changes

2023-03-08 19:49 UTC, merged