Solve Misleading Minimum Order Size Message in Binance Brokerage bug …
QuantConnect/Lean pull request #7218
Opened 2023-04-26 18:31 UTC by hungnguyen9

#### Description
Misleading Minimum Order Size Message in Binance Brokerage #7215 

#### Related Issue
Close #7215 

#### Requires Documentation Change
No

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

2023-04-27 13:44 UTC, AlexCatarino requested changes
Thank you, @hungnguyen9.

Please add unit tests. I ran the unit tests (see [BinanceBrokerageModelTests.cs](https://github.com/QuantConnect/Lean/blob/master/Tests/Common/Brokerages/BinanceBrokerageModelTests.cs#L30)), and they didn't change, since we are not validating the message content (only if it's `null`: [example](https://github.com/QuantConnect/Lean/blob/master/Tests/Common/Brokerages/BinanceBrokerageModelTests.cs#L67)))

2023-04-27 13:44 UTC, AlexCatarino commented on Common/Brokerages/BinanceBrokerageModel.cs
>                      quantityIsValid &= IsOrderSizeLargeEnough(limitOrder.LimitPrice);
You could save `price` here: `price = limitOrder.LimitPrice`, and in every `case` accordingly. It would avoid duplication.

2023-04-29 00:51 UTC, jaredbroad commented
Welcome to LEAN @hungnguyen9! 🙌 Thank you for the contribution

2023-05-10 22:49 UTC, Martin-Molinero commented
Thanks @hungnguyen9! Closing for now until reviews are addressed 👍

2023-05-10 22:49 UTC, closed without merging