Add Missing Python Version of TickDataFilteringAlgorithm (#7219)
QuantConnect/Lean pull request #7222
Opened 2023-04-26 22:36 UTC by hungnguyen9

#### Description
Missing Python Version of TickDataFilteringAlgorithm #7219 

#### Related Issue
Close #7219 

#### Requires Documentation Change

No

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

2023-04-26 22:48 UTC, AlexCatarino requested changes
Thank you for the contribution, @hungnguyen9 .

I ran this algorithm on QuantConnect Cloud and it raised the following exception:

```
During the algorithm initialization, the following exception has occurred: object does not implement ISecurityDataFilter
  at Initialize
```

2023-04-27 07:55 UTC, hungnguyen9 commented
> Thank you for the contribution, @hungnguyen9 .
> 
> I ran this algorithm on QuantConnect Cloud and it raised the following exception:
> 
> ```
> During the algorithm initialization, the following exception has occurred: object does not implement ISecurityDataFilter
>   at Initialize
> ```

2023-04-27 07:57 UTC, hungnguyen9 commented
> Thank you for the contribution, @hungnguyen9 .
> 
> I ran this algorithm on QuantConnect Cloud and it raised the following exception:
> 
> ```
> During the algorithm initialization, the following exception has occurred: object does not implement ISecurityDataFilter
>   at Initialize
> ```

Dear @AlexCatarino,

Thank you very much for your comment. I have modified the code. Could you please check again?

2023-04-27 12:40 UTC, AlexCatarino submitted a review, later dismissed
Hi @hungnguyen9 ,

Please copy your algorithm, and run a backtest in QuantConnect Cloud. It should not raise exceptions. I ran the latest version and got the following:

```
During the algorithm initialization, the following exception has occurred: Trying to dynamically access a method that does not exist throws a TypeError exception. To prevent the exception, ensure each parameter type matches those required by the 'main.TickDataFilteringAlgorithm'>) method. Please checkout the API documentation.
  at Initialize
    self.Securities["SPY"].DataFilter = ExchangeDataFilter(self)
```

I recommend looking #7201 , since it has added the features that make this algorithm possible.

We have also added Documentation on:
https://www.quantconnect.com/docs/v2/writing-algorithms/securities/filtering-data

2023-04-27 12:40 UTC, AlexCatarino commented on Algorithm.Python/TickDataFilteringAlgorithm.py
> +    def ExchangeDataFilter(self, algo):
This should be `def __init__` and call `super()` this the class inherits from `SecurityDataFilter`. However, this class might not need to inherit from `SecurityDataFilter`.

2023-05-07 08:14 UTC, hungnguyen9 commented
> Hi @hungnguyen9 ,
> 
> Please copy your algorithm, and run a backtest in QuantConnect Cloud. It should not raise exceptions. I ran the latest version and got the following:
> 
> ```
> During the algorithm initialization, the following exception has occurred: Trying to dynamically access a method that does not exist throws a TypeError exception. To prevent the exception, ensure each parameter type matches those required by the 'main.TickDataFilteringAlgorithm'>) method. Please checkout the API documentation.
>   at Initialize
>     self.Securities["SPY"].DataFilter = ExchangeDataFilter(self)
> ```
> 
> I recommend looking #7201 , since it has added the features that make this algorithm possible.
> 
> We have also added Documentation on: https://www.quantconnect.com/docs/v2/writing-algorithms/securities/filtering-data

Hi @AlexCatarino,

Thank you for your comment. I have modified my code, ran a backtest in QC cloud and it looked okay. Could you please check my PR again?

Regards,
Hung

2023-05-10 22:47 UTC, Martin-Molinero approved these changes
Thanks @hungnguyen9!

2023-05-10 22:48 UTC, merged