Fix bug in VolumeWeightedAveragePriceIndicator
QuantConnect/Lean pull request #7336
Opened 2023-06-27 21:11 UTC by Marinovsky

#### Description

When this indicator was reset, instead of reset its VolumeWeightedAveragePrice composite indicator, it created a new one. So the previous was never disposed. In order to fix this, there was created a new indicator called `ResetCompositeIndicator.cs` that takes a composite indicator and an action to execute once the given indicator is reset. Therefore, when `Reset()` method is called in `VolumeWeightedAveragePriceIndicator`, the `VolumeWeightedAveragePriceIndicator` is reset instead of re-assigned. Immediately after , this `ResetCompositeIndicator` executes the given action to reset variables used in `IndicatorExtensions.WeightedBy()` method.

On the other hand, `IndicatorExtensions.cs` was reviewed to ensure this bug was not in other usages of `CompositeIndicator`
#### Related Issue

Closes #4964 
#### Motivation and Context

With this change, LEAN will no create a new composite indicator once `VolumeWeightedAveragePriceIndicator` is reset. Additionally, users will be able to assign an action to execute once certain indicator is reset.
#### Requires Documentation Change

This change does not require updates to documentation
#### How Has This Been Tested?

There was created a unit test that asserted `VolumeWeightedAveragePrice` field in `VolumeWeightedAveragePriceIndicator.cs` was the same before and after the indicator was reset
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-06-28 13:29 UTC, jhonabreul requested changes
Nice! Leaving a few comments:

- Could also add unit tests for this new `ResetCompositeIndicator` class, creating a composite indicator (any), wrapping it up with this class, updating until ready, resetting and asserting the state of each single indicator/part that composes it.
- Also could assert that each `CompositeIndicator` property when accessed in an instance of `ResetCompositeIndicator` is properly bypassed to the inner composite indicator. 
- Having these tests might be enough to revert changes in `Indicators/VolumeWeightedAveragePriceIndicator.cs` and keeping _vwap private and as a `CompositeIndicator`.

2023-06-28 13:29 UTC, jhonabreul commented on Indicators/IndicatorExtensions.cs
> +        public static ResetCompositeIndicator WeightedBy<T, TWeight>(this IndicatorBase<T> value, TWeight weight, int period)
`ResetCompositeIndicator` can be a `CompositeIndicator` that overrides the `Reset` method, that way we don't change the `WeightedBy` API (keep returning `CompositeIndicator`) and users can still access every member of the `CompositeIndicator` as per usual.

2023-06-28 13:29 UTC, jhonabreul commented on Indicators/ResetCompositeIndicator.cs
> +    /// Class that extends CompositeIndicator to execute a given action once is reset
As commented in `WeightedBy` (and also in this summary), we can extend `CompositeIndicator`.

2023-06-28 13:29 UTC, jhonabreul commented on Indicators/ResetCompositeIndicator.cs
> +        public override bool IsReady => _compositeIndicator.IsReady;
It should also override the remaining `CompositeIndicator` properties so that the users can access the inner composite indicator instance properties.

2023-06-28 13:29 UTC, jhonabreul commented on Indicators/ResetCompositeIndicator.cs
> +        /// <returns></returns>
Missing param and returns comments

2023-06-28 13:29 UTC, jhonabreul commented on Tests/Indicators/VolumeWeightedAveragePriceIndicatorTests.cs
> +            Assert.IsTrue(Object.ReferenceEquals(lastVWAP, newVWAP));
Perhaps assert new state (number of samples/not ready) of the VWAP after reset

2023-06-29 14:18 UTC, jhonabreul approved these changes
Thank you! 🚀

2023-06-29 18:26 UTC, Martin-Molinero approved these changes
Nice! minor comment 👍

2023-06-29 18:26 UTC, Martin-Molinero commented on Indicators/VolumeWeightedAveragePriceIndicator.cs
> -            _volume.Reset();
We should still reset `_price/_volume` I think?

2023-06-29 22:51 UTC, Martin-Molinero approved these changes

2023-06-30 16:36 UTC, merged