Collective2 module modernization and finalization
QuantConnect/Lean pull request #7435
Opened 2023-08-18 09:52 UTC by francis2

Removed platformId support from C2.
Modernized C2 API calls to APIv4.
Added C2 rate limiters (RateGate).
Added response logging so users can easily debug their code. Added a few symbols for the demo.

#### Description
Collective2 Module and a DemonstrationAlgorithm

#### Related Issue
I am not aware of any related open issues

#### Motivation and Context
Modernize and finalize module

#### Requires Documentation Change
None

#### How Has This Been Tested?
Collective2SignalExportDemonstrationAlgorithm contains a list of symbols that produce expected results.

#### Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [ X] My code follows the code style of this project.
- [ X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ X] I have added tests to cover my changes. 
- [X ] All new and existing tests passed.
- [ X] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-08-18 18:22 UTC, Martin-Molinero requested changes
Hey @francis2! Thank you for the PR, leaving a couple of requests 👍

2023-08-18 18:22 UTC, Martin-Molinero commented on Common/Algorithm/Framework/Portfolio/SignalExports/Collective2SignalExport.cs
> +        static string PrintErrors(List<ResponseError> errors)
Please add the missing `private` access modifier to match existing code style👍

2023-08-18 23:05 UTC, Martin-Molinero commented on Algorithm.CSharp/Collective2PortfolioSignalExportDemonstrationAlgorithm.cs
>      public class Collective2PortfolioSignalExportDemonstrationAlgorithm : QCAlgorithm, IRegressionAlgorithmDefinition
It seems another unit test needs an update too 
<img width="1004" alt="image" src="https://github.com/QuantConnect/Lean/assets/18473240/5de8bb43-4258-4bc7-bcb4-41622bc1770e">

2023-08-28 11:27 UTC, francis2 commented on Common/Algorithm/Framework/Portfolio/SignalExports/Collective2SignalExport.cs
> +            HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _apiKey);
It needs to be in every message header

2023-08-28 23:53 UTC, Martin-Molinero commented
Reviews addressed in https://github.com/QuantConnect/Lean/pull/7448, closing this PR since included

2023-08-28 23:53 UTC, closed without merging