Add Unit Tests for IPortfolioOptimizer Classes
QuantConnect/Lean pull request #7691
Opened 2024-01-11 18:03 UTC by wtindall1

#### Description

Added unit tests for IPortfolioOptimizer implementations:
- MaximumSharpeRatioPortfolioOptimizer
- MinimumVariancePortfolioOptimizer
- UnconstrainedMeanVariancePortfolioOptimizer

#### Related Issue

 Closes #4494 

#### Motivation and Context

The implementations were not covered by unit tests.

#### Requires Documentation Change

No

#### How Has This Been Tested?

Ran the new and existing tests.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-01-15 14:12 UTC, jhonabreul requested changes
Thanks for your contribution 🚀 Just leaving a couple minor comments

2024-01-15 14:12 UTC, jhonabreul commented on Tests/Algorithm/Framework/Portfolio/MaximumSharpeRatioPortfolioOptimizerTests.cs
> +            double[,] historicalReturns1 = new double[,] { { 0.02, -0.02, 0.28 }, { -0.50, -0.29, -0.13 }, { 0.81, 0.29, 0.31 }, { -0.03, -0.00, 0.01 } };
In Lean it is a common practice to use prioritize the use of `var` vs. explicitly typing the variable

2024-01-15 14:12 UTC, jhonabreul commented on Tests/Algorithm/Framework/Portfolio/MaximumSharpeRatioPortfolioOptimizerTests.cs
> +        private Dictionary<int, double[]> _expectedResults = new();
The keys are just indices, perhaps a list or array would be enough?

2024-01-16 19:58 UTC, jhonabreul approved these changes
Thank you!

2024-01-17 19:09 UTC, Martin-Molinero reviewed
Thank you @wtindall1!
Leaving a couple of comments. It seems there's room to create a base `PortfolioOptimizerTest` class which defines shared cases to be tested and each override can just define the result it produces.
If your interested think we should add some tests for the `RiskParityPortfolioOptimizer` & the `PortfolioOptimizerPythonWrapper`

2024-01-17 19:09 UTC, Martin-Molinero commented on Tests/Algorithm/Framework/Portfolio/MinimumVariancePortfolioOptimizerTests.cs
> +        public void TestOptimizeWeightingsSpecifyingTargetReturns(int testCaseNumber)
Let's remove `Test` from the test names, same comment for the other tests & files 👍

2024-01-17 19:09 UTC, Martin-Molinero commented on Tests/Algorithm/Framework/Portfolio/MinimumVariancePortfolioOptimizerTests.cs
> +        public void SingleSecurityPortfolioReturnsOne()
These are missing the `[Test]` attribute, same for `UnconstrainedMeanVariancePortfolioOptimizer`

2024-01-17 22:04 UTC, wtindall1 commented
Hi @Martin-Molinero - thanks for the review, I will address your comments. For the `RiskParityPortfolioOptimizer` , is this not covered by the `RiskParityPortfolioOptimizerTests` class, or is there additional coverage you were hoping for?

2024-01-17 23:09 UTC, Martin-Molinero commented
> For the RiskParityPortfolioOptimizer , is this not covered by the RiskParityPortfolioOptimizerTests class

Oh nice, sorry didn't realize 👍 existing tests look good. For `PortfolioOptimizerPythonWrapper` can take a look for inspiration at `BrokerageModelTests` basically testing the wrapping functionality of a python wrapper

2024-01-19 15:13 UTC, Martin-Molinero approved these changes
Nice work @wtindall1! Thank you 🚀

2024-01-19 15:14 UTC, merged