Option Strategy: Jelly Roll
QuantConnect/Lean pull request #8092
Opened 2024-06-17 12:11 UTC by LouisSzeto

#### Description
- Add new abstraction of option strategy Long and Short Jelly Roll

margin requirement from IB:
- Long Jelly Roll
![Screenshot 2024-06-14 163231](https://github.com/QuantConnect/Lean/assets/56447733/53ec98dc-cc33-4926-bf94-e4ca96b8d04a)

- Short Jelly Roll
![Screenshot 2024-06-14 163428](https://github.com/QuantConnect/Lean/assets/56447733/ae298687-7ef6-4806-92d2-bec48a271547)

#### Related Issue

#### Motivation and Context
no helper

#### Requires Documentation Change
Add new section in Option Strategy

#### How Has This Been Tested?
- unit tests
- regression tests

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-06-25 14:31 UTC, Martin-Molinero requested changes
Cool! Leaving a few requests 👍

2024-06-25 14:31 UTC, Martin-Molinero commented on Common/Securities/Option/StrategyMatcher/OptionStrategyDefinitions.cs
> +        /// expiration.
Docs are off, please review all docs

2024-06-25 14:31 UTC, Martin-Molinero commented on Common/Securities/Option/OptionStrategies.cs
> +            decimal leg3Strike,
Believe `higherStrike/middleStrike/lowerStrike` would be better names, like we use in the other strategies, same comment for the other ones

2024-06-25 14:31 UTC, Martin-Molinero commented on Common/Securities/Option/StrategyMatcher/OptionStrategyDefinitions.cs
> +        /// Bear Call Ladder strategy is long 1 put and short 2 puts, with descending strike prices in order,
> Bear Call Ladder

Off, please self review in detail

2024-06-25 14:31 UTC, Martin-Molinero commented on Common/Securities/Option/OptionStrategyPositionGroupBuyingPowerModel.cs
> +                // Bear Put Ladder = Bear Put Spread of 2 lower strike prices (margin: 0) + Short Naked Put with the highest strike price
Seems these option strategies are actually a combination of others, we should reuse their margin requirement calculations and avoid having to duplicate the implementations, can extract implementation into some private method/abstraction if easier

2024-06-25 14:31 UTC, Martin-Molinero commented
Mind sharing where the option strategy definitions were sourced from, given they are not in the core IB list

2024-06-25 14:42 UTC, Martin-Molinero commented
Please rebase from master, the regression test interface was changed & a unit test CI bug was shipped

2024-06-26 01:29 UTC, LouisSzeto commented
> Mind sharing where the option strategy definitions were sourced from, given they are not in the core IB list

I've updated the description now 😄

2024-06-26 18:05 UTC, Martin-Molinero requested changes

2024-06-27 18:54 UTC, Martin-Molinero approved these changes
Thank you 👍

2024-06-27 18:58 UTC, merged