Add new indicator - ZLEMA - Zero Lag Exponential Moving Average
QuantConnect/Lean pull request #8148
Opened 2024-07-05 11:38 UTC by femtotrader

#### Description

Implement new indicator - ZLEMA - Zero Lag Exponential Moving Average

#### Related Issue
#8118

#### Motivation and Context

The Zero Lag Exponential Moving Average (ZLEMA) indicator was developed by John Ehlers and Ric Way. The objective is to eliminate the inherent lag associated with all trend following indicators such as averages.

#### Requires Documentation Change

Doc for this indicator should be created

#### How Has This Been Tested?

comparison with talipp computation of ZLEMA(5) of SPY close prices

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-07-05 14:59 UTC, AlexCatarino commented on Tests/Indicators/ZeroLagExponentialMovingAverageTests.cs
> +        protected override string TestFileName => "spy_with_zlema.csv";
Could you please provide the code used to generate this file?
Please check out the following: https://github.com/QuantConnect/Lean/issues/4166#issuecomment-1777061450

2024-07-05 19:07 UTC, Martin-Molinero requested changes
Hey @femtotrader!
Welcome to Lean & nice work 🙌, leaving some requests and suggestions. Believe many of them apply to the other indicators PRs please take them into consideration and address given this is the first review being done👍

2024-07-05 19:07 UTC, Martin-Molinero commented on Tests/TestData/generate_reference_data_from_talipp.py
> +def main():
Nice!

2024-07-05 19:09 UTC, Martin-Molinero commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +        private readonly RollingWindow<IndicatorDataPoint> _rolling_window;
Or actually a better name would be something like `_delayedPrice` being a Delay indicator?

2024-07-05 19:47 UTC, femtotrader commented on Tests/TestData/generate_reference_data_from_talipp.py
> +def main():
I'm more a Python guy than C#

2024-07-05 19:56 UTC, femtotrader commented on Tests/Indicators/ZeroLagExponentialMovingAverageTests.cs
> +            //TestHelper.AssertIndicatorIsInDefaultState(zlema._ema);
Sorry but I didn't understood your last comment here

2024-07-05 20:02 UTC, Martin-Molinero commented on Tests/Indicators/ZeroLagExponentialMovingAverageTests.cs
> +            //TestHelper.AssertIndicatorIsInDefaultState(zlema._ema);
Just replacing `DateTime.UtcNow`  for specific date time instances `new DateTime(2024, 07, 05, X, Y, Z)`, believe makes it more deterministic & performant

2024-07-05 20:06 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +    /// Represents the zero lag moving average indicator (ZLEMA)
Done

2024-07-05 20:11 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +        private readonly RollingWindow<IndicatorDataPoint> _rolling_window;
Done

2024-07-05 20:14 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +            } else {
Done

2024-07-05 20:27 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +        public int WarmUpPeriod => _period + (int)Math.Floor(((float)_period) / 2);
I don't see where I should use override. When I set this property as private tests are failing. 

When I use

```
        private override int WarmUpPeriod
        {
            get { return _period + (int)Math.Floor(((float)_period) / 2); }
        }
```

compiler is complaining like so


```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0621	'ZeroLagExponentialMovingAverage.WarmUpPeriod': virtual or abstract members cannot be private	QuantConnect.Indicators	C:\Users\Admin\git\github\femto\Lean\Indicators\ZeroLagExponentialMovingAverage.cs	96	
Error (active)	CS0507	'ZeroLagExponentialMovingAverage.WarmUpPeriod': cannot change access modifiers when overriding 'public' inherited member 'WindowIndicator<IndicatorDataPoint>.WarmUpPeriod'	QuantConnect.Indicators	C:\Users\Admin\git\github\femto\Lean\Indicators\ZeroLagExponentialMovingAverage.cs	96	
```

2024-07-05 21:06 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +            _rolling_window = new RollingWindow<IndicatorDataPoint>(_lag + 1);
Done

2024-07-05 21:07 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +            if (Samples >= _lag + 1)
Done

2024-07-05 21:07 UTC, femtotrader commented on Indicators/ZeroLagExponentialMovingAverage.cs
> +using static QuantConnect.Messages;
They have been removed

2024-07-08 14:58 UTC, merged

2024-07-08 21:00 UTC, AlexCatarino commented
This PR didn't add `MovingAverageType.Zlema` to [MovingAverageType.cs](https://github.com/QuantConnect/Lean/blob/master/Indicators/MovingAverageType.cs#L21) and [MovingAverageTypeExtensions.cs](https://github.com/QuantConnect/Lean/blob/master/Indicators/MovingAverageTypeExtensions.cs#L23).

2024-07-08 21:16 UTC, femtotrader commented
Good catch @AlexCatarino 
I'm going to sleep. Maybe @Martin-Molinero can tackle this.
Sorry for forgeting this