Implement new indicator VWMA
QuantConnect/Lean pull request #8161
Opened 2024-07-06 06:45 UTC by femtotrader

#### Description

Implement new indicator - VWMA (Volume Weighted Moving Average)

#### Related Issue
#8128

#### Motivation and Context
The VWMA indicator wasn't implemented.
(not to be  confused with VWAP)

#### Requires Documentation Change

Doc for this indicator should be created but some docstring are written

#### How Has This Been Tested?

comparison with talipp computation of VWMA(20) of SPY candle data

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-07-06 06:46 UTC, femtotrader commented
The followings tests are failing
- `AcceptsRenkoBarsAsInput`
- `WarmsUpProperly`
but others are passing.

Any idea?

2024-07-06 07:06 UTC, femtotrader commented
The followings test is failing
- `AcceptsRenkoBarsAsInput`
but others are passing.

Any idea?

2024-07-09 14:21 UTC, AlexCatarino commented
Since this is a moving average, we need to add it to the MovingAverageType enum after https://github.com/QuantConnect/Lean/pull/8177 is merged.

2024-07-09 19:14 UTC, femtotrader commented
Will also add

            indicator = MovingAverageType.VWMA.AsIndicator(name, 9);
            Assert.IsInstanceOf(typeof(VolumeWeightedMovingAverage), indicator);

to

    MovingAverageTypeExtensionsTests.cs

2024-07-12 20:48 UTC, femtotrader commented
I wonder how I can add VWMA to MovingAverageTypeExtensions.

This kind of MA is a bit different from others because it takes a bar as input... not a price.

Adding 


                case MovingAverageType.VWMA:
                    return new VolumeWeightedMovingAverage(period);

to MovingAverageTypeExtensions.cs ... next to others MA

and I'm getting a compile error

    Severity	Code	Description	Project	File	Line	Suppression State	Details
    Error (active)	CS0029	Cannot implicitly convert type 'QuantConnect.Indicators.VolumeWeightedMovingAverage' to 'QuantConnect.Indicators.IndicatorBase<QuantConnect.Indicators.IndicatorDataPoint>'	QuantConnect.Indicators	C:\Users\Admin\git\github\femto\Lean\Indicators\MovingAverageTypeExtensions.cs	76

2024-07-15 15:48 UTC, Martin-Molinero requested changes
Hey @femtotrader! Cool!
Smees this PR needs to address similar previous reviews, posting. Please review all PRs and address these reviews. At this point should focus 💯 on getting existing PRs ready, not opening new PRs for now 👍

2024-07-15 15:48 UTC, Martin-Molinero commented on Indicators/VolumeWeightedMovingAverage.cs
> +        private IndicatorBase<IndicatorDataPoint> _rollingSumV { get; }
Smees this PR is missing to address previous reviews, 
- XML description improvement
- privates should be fields, no need to be properties
- `..SumS/..SumV` should be expanded to their complete names
- please push `IsReady` above constructor
- variable `_sumV` in method scope name is off codying style
- missing brackets
-

2024-07-15 15:48 UTC, Martin-Molinero commented on Algorithm/QCAlgorithm.Indicators.cs
> +        /// <returns>A new AverageTrueRange indicator with the specified smoothing type and period</returns>
- XML documentation seems off, copy/paste
- `InitializeIndicator` needs to receive the symbol too, please take a look at how it works 👍

2024-07-15 19:09 UTC, Martin-Molinero approved these changes
Thank you 👍

2024-07-16 14:14 UTC, merged