Implement new indicator CHOP - Choppiness Index
QuantConnect/Lean pull request #8178
Opened 2024-07-09 07:36 UTC by femtotrader

#### Description

Implement new indicator CHOP - Choppiness Index

#### Related Issue

#8122 

#### Motivation and Context

This indicator wasn't implemented in QuantConnect Lean

#### Requires Documentation Change

#### How Has This Been Tested?

Comparison with talipp computation of CHOP(14) of SPY candles

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-07-19 12:24 UTC, Martin-Molinero requested changes
Thank you 👍 Leaving minor requests

2024-07-20 09:57 UTC, femtotrader commented on Indicators/ChoppinessIndex.cs
> +            if (IsReady)
Fixed useless IsReady test

CHOP14 is available after 14 incoming data. So I think it's

    WarmUpPeriod= period

True Range return value even after only one incoming data... it's not ready and fully initalized but it return data that is used by RollingWindow (_trueRangeHistory).

2024-07-20 09:58 UTC, femtotrader commented on Indicators/ChoppinessIndex.cs
> +        private readonly RollingWindow<float> _trueRangeHistory;
Fixed by using `decimal` instead

2024-07-20 09:59 UTC, femtotrader commented on Tests/Indicators/ChoppinessIndexTests.cs
> +            //VolumeRenkoBarSize = 0.5m;  // AcceptsVolumeRenkoBarsAsInput is hanging when uncommented
It really stuck!
I also tried changing VolumeRenkoBarSize to 1m or 2m... but it's still blocking here

2024-07-20 18:55 UTC, Martin-Molinero approved these changes
Nice! 🚀

2024-07-22 15:14 UTC, merged