Made changes in the ParseOptionTickerOSI function. Now it can handle …
QuantConnect/Lean pull request #8219
Opened 2024-07-22 15:34 UTC by keshavdalmia10

…both with and without space

#### Description

#### Related Issue

#### Motivation and Context

#### Requires Documentation Change

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [ ] All new and existing tests passed.
- [ ] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-07-22 15:49 UTC, keshavdalmia10 commented
Just changed the branch name right now. Will make the necessary changes as you requested.
Thanks

2024-07-22 18:09 UTC, keshavdalmia10 commented
Hi @Martin-Molinero , I have made the changes you told. If any further changes required feel free to tell. 
Thanks.

2024-07-22 20:01 UTC, Martin-Molinero requested changes
Thanks! almost there 👍

2024-07-22 20:01 UTC, Martin-Molinero commented on Common/SymbolRepresentation.cs
> +        return Invariant($"{underlying}{expiration.ToStringInvariant(DateFormat.SixCharacter)}{right.ToStringPerformance()[0]}{(strikePrice * 1000m):00000000}");
Indentation is wrong for the lines in these 2 new methods? missing 1 tab/level deeper it seems

2024-07-22 20:01 UTC, Martin-Molinero commented on Tests/Common/SymbolRepresentationTests.cs
> +        public void GenerateOptionTickerOSICompact_ValidInputs(string underlying, OptionRight right, decimal strikePrice, string date, string expected)
Nice!

2024-07-22 20:01 UTC, Martin-Molinero commented on Tests/Common/SymbolRepresentationTests.cs
>          public void ParseOptionTickerOSI(string optionStr, SecurityType securityType, OptionStyle optionStyle,
Let's please add assertion on the expected `decimal strikePrice, string date` as done below 👍

2024-07-23 04:48 UTC, keshavdalmia10 commented
Hi @Martin-Molinero, I have made the requested changes.
Thanks

2024-07-23 13:50 UTC, Martin-Molinero commented
Thank you @keshavdalmia10! Nice work 🚀

2024-07-23 14:23 UTC, merged